export const fixedNameMap = new Map([
    ['nidoran-f', {id: 29, name: 'nidoran', gif: 'nidoran_f' }],
    ['nidoran-m', {id: 32, name: 'nidoran', gif: 'nidoran_m' }],
    ['mr-mime', {id: 112, name: 'mr. mime', gif: 'mr.mime' }],
    ['ho-oh', {id: 250, name: 'ho-oh', gif: 'ho-oh' }],
    ['deoxys-normal', {id: 386, name: 'deoxys', gif: 'deoxys' }],
    ['wormadam-plant', {id: 413, name: 'wormadam', gif: 'wormadam' }],
    ['mime-jr', {id: 439, name: 'mime jr.', gif: 'mime_jr' }],
    ['porygon-z', {id: 474, name: 'porigon z', gif: 'porygon-z' }],
    ['giratina-altered', {id: 487, name: 'giratina', gif: 'giratina' }],
    ['shaymin-land', {id: 492, name: 'shaymin', gif: 'shaymin' }],
    ['basculin-red-striped', {id: 550, name: 'basculin', gif: 'basculin' }],
    ['darmanitan-standard', {id: 555, name: 'darmanitan', gif: 'darmanitan' }],
    ['tornadus-incarnate', {id: 641, name: 'tornadus', gif: 'tornadus' }],
    ['thundurus-incarnate', {id: 642, name: 'thundurus', gif: 'thundurus' }],
    ['landorus-incarnate', {id: 645, name: 'landorus', gif: 'landorus' }],
    ['keldeo-ordinary', {id: 647, name: 'keldeo', gif: 'keldeo' }],
    ['meloetta-aria', {id: 648, name: 'meloetta', gif: 'meloetta' }],
    ['meowstic-male', {id: 678, name: 'meowstic', gif: 'meowstic' }],
    ['aegislash-shield', {id: 681, name: 'aegislash', gif: 'aegislash' }],
    ['pumpkaboo-average', {id: 710, name: 'pumpkaboo', gif: 'pumpkaboo' }],
    ['gourgeist-average', {id: 711, name: 'gourgeist', gif: 'gourgeist' }],
    ['zygarde-50', {id: 718, name: 'zygarde', gif: 'zygarde' }],
    ['oricorio-baile', {id: 741, name: 'oricorio', gif: 'oricorio' }],
    ['lycanroc-midday', {id: 745, name: 'lycanroc', gif: 'lycanroc' }],
    ['wishiwashi-solo', {id: 746, name: 'wishiwashi', gif: 'wishiwashi' }],
    ['type-null', {id: 772, name: 'type: null', gif: 'typenull' }],
    ['minior-red-meteor', {id: 774, name: 'minior', gif: 'minior' }],
    ['mimikyu-disguised', {id: 778, name: 'mimikyu', gif: 'mimikyu' }],
    ['jangmo-o', {id: 782, name: 'jangmo-o', gif: 'jangmo-o' }],
    ['hakamo-o', {id: 783, name: 'hakamo-o', gif: 'hakamo-o' }],
    ['kommo-o', {id: 784, name: 'kommo-o', gif: 'kommo-o' }],
    ['tapu-koko', {id: 785, name: 'tapu koko', gif: 'tapukoko' }],
    ['tapu-lele', {id: 786, name: 'tapu lele', gif: 'tapulele' }],
    ['tapu-bulu', {id: 787, name: 'tapu bulu', gif: 'tapubulu' }],
    ['tapu-fini', {id: 788, name: 'tapu fini', gif: 'tapufini' }],
])
