export const fixedNameMap = new Map([
    ['nidoran-f', {id: 29, name: 'nidoran' }],
    ['nidoran-m', {id: 32, name: 'nidoran' }],
    ['mr-mime', {id: 112, name: 'mr. mime' }],
    ['ho-oh', {id: 250, name: 'ho-oh' }],
    ['deoxys-normal', {id: 386, name: 'deoxys' }],
    ['wormadam-plant', {id: 413, name: 'wormadam' }],
    ['mime-jr', {id: 439, name: 'mime jr.' }],
    ['porygon-z', {id: 474, name: 'porigon z' }],
    ['giratina-altered', {id: 487, name: 'giratina' }],
    ['shaymin-land', {id: 492, name: 'shaymin' }],
    ['basculin-red-striped', {id: 550, name: 'basculin' }],
    ['darmanitan-standard', {id: 555, name: 'darmanitan' }],
    ['tornadus-incarnate', {id: 641, name: 'tornadus' }],
    ['thundurus-incarnate', {id: 642, name: 'thundurus' }],
    ['landorus-incarnate', {id: 645, name: 'landorus' }],
    ['keldeo-ordinary', {id: 647, name: 'keldeo' }],
    ['meloetta-aria', {id: 648, name: 'meloetta' }],
    ['meowstic-male', {id: 678, name: 'meowstic' }],
    ['aegislash-shield', {id: 681, name: 'aegislash' }],
    ['pumpkaboo-average', {id: 710, name: 'pumpkaboo' }],
    ['gourgeist-average', {id: 711, name: 'gourgeist' }],
    ['zygarde-50', {id: 718, name: 'zygarde' }],
    ['oricorio-baile', {id: 741, name: 'oricorio' }],
    ['lycanroc-midday', {id: 745, name: 'lycanroc' }],
    ['wishiwashi-solo', {id: 746, name: 'wishiwashi' }],
    ['type-null', {id: 772, name: 'type: null' }],
    ['minior-red-meteor', {id: 774, name: 'minior' }],
    ['mimikyu-disguised', {id: 778, name: 'mimikyu' }],
    ['jangmo-o', {id: 782, name: 'jangmo-o' }],
    ['hakamo-o', {id: 783, name: 'hakamo-o' }],
    ['kommo-o', {id: 784, name: 'kommo-o' }],
    ['tapu-koko', {id: 785, name: 'tapu koko' }],
    ['tapu-lele', {id: 786, name: 'tapu lele' }],
    ['tapu-bulu', {id: 787, name: 'tapu bulu' }],
    ['tapu-fini', {id: 788, name: 'tapu fini' }],
])
